language: node_js

env:
  - ARCH=x64
  - ARCH=arm

node_js: "8.11.3"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libavahi-compat-libdnssd-dev git
  - npm config set strict-ssl false
  - nvm install 8.11.3
  - nvm use 8.11.3
  - npm install -g --unsafe-perm homebridge

before_script:
  - "npm install -g homebridge-garage-door-wsensor"
  - "mkdir .homebridge"
  - "cp config.sample.json .homebridge/config.json"

script: "homebridge & sleep 30; kill $!;"

